language: go
go: 1.7
sudo: false
dist: trusty

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
 - go get github.com/thraxil/resize
 - go get github.com/golang/groupcache

script:
  - goveralls -service=travis-ci -package=.
