language: go
go: 1.4

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
 - go get github.com/thraxil/resize
 - go get github.com/golang/groupcache

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
